//! Write `/etc/resolv.conf`.

#[cfg(target_os = "linux")]
use crate::apply::NetError;

#[cfg(target_os = "linux")]
pub fn write_resolv_conf(nameservers: &[String]) -> Result<(), NetError> {
    use std::fs;
    use std::io::Write;

    let mut body = String::from("# Generated by pertisk-net\n");
    for ns in nameservers {
        body.push_str(&format!("nameserver {ns}\n"));
    }
    let _ = fs::create_dir_all("/etc");
    let mut f = fs::File::create("/etc/resolv.conf")?;
    f.write_all(body.as_bytes())?;
    tracing::info!(?nameservers, "wrote /etc/resolv.conf");
    Ok(())
}
