[package]
name = "pertisk-api"
description = "Pertisk KOS management API (gRPC)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
http = "1"
pertisk-bootstrap = { workspace = true }
pertisk-config = { workspace = true }
pertisk-disk = { workspace = true }
pertisk-net = { workspace = true }
pertisk-proto = { workspace = true }
pertisk-tpm = { workspace = true }
pertisk-update = { workspace = true }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile = "2"
serde_yaml = { workspace = true }
serde_json = "1"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = "0.1"
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
tonic = { workspace = true }
tower = "0.5"
tracing = { workspace = true }
ureq = { version = "2", default-features = false, features = ["tls", "json"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[dev-dependencies]
rcgen = { version = "0.14", features = ["pem"] }
tempfile = "3"
