[package]
name = "pertisk-kubelet"
description = "Pertisk KOS kubelet process manager"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
pertisk-config = { workspace = true }
pertisk-net = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ureq = { version = "2", default-features = false, features = ["tls"] }
