[package]
name = "pertiskctl"
description = "Pertisk KOS CLI (talosctl-style)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "pertiskctl"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
base64 = "0.22"
clap = { workspace = true }
pertisk-bootstrap = { workspace = true }
pertisk-config = { workspace = true }
pertisk-proto = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
